### ISSUE TITLE
Runtime panic with copy from B2 to GCD with -threads > 1

### ISSUE THREAD

**Issue by jkl1337** [gilbertchen/duplicacy#177]
The following is with duplicacy 2.0.7 tag.
Default is a B2 storage. This happens when attempting to copy to a GCD storage that was newly added:

```
$ duplicacy copy -from default -to gcd -threads 12 -r 3

Source storage set to b2://duplicacy
Destination storage set to gcd://duplicacy
runtime error: index out of range
goroutine 49 [running]:
runtime/debug.Stack(0x22, 0x0, 0x0)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
        /home/archpak/duplicacy/src/duplicacy-2.0.7/duplicacy/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:177 +0x1ad
panic(0xc3fe00, 0x11f8890)
        /usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/gilbertchen/duplicacy/src.(*B2Storage).GetFileInfo(0xc4201c2930, 0x7, 0xc420456000, 0x47, 0x40, 0xc420456000, 0x47, 0x20)
        /home/archpak/duplicacy/src/duplicacy-2.0.7/duplicacy/src/github.com/gilbertchen/duplicacy/src/duplicacy_b2storage.go:188 +0x2f1
github.com/gilbertchen/duplicacy/src.(*B2Storage).FindChunk(0xc4201c2930, 0x7, 0xc4203b6840, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/archpak/duplicacy/src/duplicacy-2.0.7/duplicacy/src/github.com/gilbertchen/duplicacy/src/duplicacy_b2storage.go:214 +0x9d
github.com/gilbertchen/duplicacy/src.(*ChunkDownloader).Download(0xc420473ea0, 0x7, 0x0, 0x0, 0xc4204f1940, 0x20, 0x0, 0x1, 0xc4200160a8)
        /home/archpak/duplicacy/src/duplicacy-2.0.7/duplicacy/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:301 +0x12a
github.com/gilbertchen/duplicacy/src.CreateChunkDownloader.func1(0xc420473ea0, 0x7)
        /home/archpak/duplicacy/src/duplicacy-2.0.7/duplicacy/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:81 +0xb9
created by github.com/gilbertchen/duplicacy/src.CreateChunkDownloader
        /home/archpak/duplicacy/src/duplicacy-2.0.7/duplicacy/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:76 +0x26d
```

Removing the `-threads` argument allows success.

**Comment by gilbertchen** [comment]
This has been fixed in https://github.com/gilbertchen/duplicacy/pull/165 by @jt70471.

**Comment by jkl1337** [comment]
I apologize. Soon after I clicked send I realized I might not be running master on that test system!
