### ISSUE TITLE
Restore should not come to a full stop when a corrupt chunk is encountered.

### ISSUE THREAD

**Issue by macdanny** [gilbertchen/duplicacy#205]
This is partly a continuation of the "Duplicacy keeps stalling" issue on the duplicacy web site. I am not allowed to add more comments there because I have "reached my post limit".

---

I switched to the s3c provider, cranked up the threads to 128, and let it run. It got about 600 chunks in and then crashed:

```
2017-09-20 12:50:45.539 ERROR UPLOAD_CHUNK Failed to decrypt the chunk ca9c51caa3e5cae3e48d72b65cd80618b7e27537b51732c54e884efcce9adc88: The storage doesn't seem to be encrypted
goroutine 134 [running]:
runtime/debug.Stack(0x0, 0x0, 0xc42a62d6b8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:177 +0x13d
panic(0xc6d3a0, 0xc42834a900)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/gilbertchen/duplicacy/src.logf(0x2, 0xd1868f, 0xc, 0xd2c6f6, 0x22, 0xc42a62dd40, 0x2, 0x2)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:160 +0x1bc
github.com/gilbertchen/duplicacy/src.LOG_ERROR(0xd1868f, 0xc, 0xd2c6f6, 0x22, 0xc42a62dd40, 0x2, 0x2)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:98 +0x73
github.com/gilbertchen/duplicacy/src.(*ChunkDownloader).Download(0xc42876cf00, 0x47, 0x0, 0x27d, 0xc42abb77e0, 0x20, 0x331d30, 0x1, 0xc4265e4e01)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:336 +0x547
github.com/gilbertchen/duplicacy/src.CreateChunkDownloader.func1(0xc42876cf00, 0x47)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:81 +0x161
created by github.com/gilbertchen/duplicacy/src.CreateChunkDownloader
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:86 +0x23f
```

This is an interesting one because it had already successfully restored over 77,000 files at this point. Maybe the issue results from the large number of threads I was using.

I also saw a bunch of messages like this.

```
2017-09-20 12:50:25.182 WARN CONFIG_CHUNK 190 chunks have been allocated
```

I suppose these are not important? It has to hold the chunks in sequence and they may arrive out of order if multiple threads are in use. I don't know why it's holding > 128 chunks though.

I switched back to s3 and started over with 16 threads. I get the same error, on the same chunk.

I think this is a sign of an undetected error when creating the initial backup to Wasabi with duplicacy.  This is why:

1. I backed up directly to Wasabi.
2. I created a new local storage using duplicacy add -copy.
3. I copied the config file and the snapshot files from Wasabi to the local storage thus created, so the same encryption keys would be used.
4. I backed up directly into my new local storage.  Since it used the same parameters including the same encryption keys, it created the very same chunks.
5. Against the local storage, I ran duplicacy check and (manually) copied missing chunks from Wasabi to the local storage until duplicacy check completed successfully.
6. Against the local storage, I ran duplicacy check with the -files option.  It took days but it completed successfully with no issues.  I am therefore absolutely confident that the local storage is OK.
7. As above ... I ran duplicacy restore to restore from Wasabi into a new repository.  It failed.
8. I downloaded the failing chunk from Wasabi and compared it to the chunk from the local storage.  They are different.  They are exactly the same size, but their contents are completely different.
9. I uploaded the chunk from the local storage into Wasabi.
10. I am now running the same restore that failed. It's still going but it is past the chunk that it was getting stuck on.

The chunk on Wasabi was wrong. This could only have happened during the backup.  Or after, I guess, if you think it's credible that bit rot did this on the Wasabi end.

It could be a problem with duplicacy or a library it depends on, or a problem with Wasabi.

The working chunk starts with "duplicacy\x00". The corrupt chunk does not. Adjacent chunks on Wasabi also start with "duplicacy\x00". So far this is the only one that doesn't.

> That chunk doesn't have a valid encryption header. Can you download it from wasabi.com and check the first 10 bytes of the file? Do you have a local copy of that chunk (if you copied from local storage to wasabi)?

Yes, I have both chunks. It's how I know they were different. The bad chunk starts with

46 ac 59 b1 59 f9 17 83 08 b8

Is there a way to tell if it's a valid but unencrypted chunk? It's definitely not encrypted because there are large swaths of repeating sequences which you shouldn't see in ciphertext.

---

I hit this now.

<pre>
2017-09-20 14:14:58.785 INFO DOWNLOAD_PROGRESS Downloaded chunk 1459 size 1126823, 3.67MB/s 1 day 14:43:08 1.3%                goroutine 25 [running]:
runtime/debug.Stack(0x0, 0x0, 0xc42abeb6b8)
        /home/flowers/.local/app/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /home/flowers/.local/app/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
        /home/flowers/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:177 +0x13d
panic(0xc88fc0, 0xc422ac6540)
        /home/flowers/.local/app/go/src/runtime/panic.go:489 +0x2cf
github.com/gilbertchen/duplicacy/src.logf(0x2, 0xd37220, 0xc, 0xd4b59b, 0x22, 0xc42abebd40, 0x2, 0x2)                                  /home/flowers/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:160 +0x1bc
github.com/gilbertchen/duplicacy/src.LOG_ERROR(0xd37220, 0xc, 0xd4b59b, 0x22, 0xc42abebd40, 0x2, 0x2)                                  /home/flowers/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:98 +0x73
github.com/gilbertchen/duplicacy/src.(*ChunkDownloader).Download(0xc428712320, 0x4, 0x0, 0x5aa, 0xc4239474c0, 0x20, 0x7eb14b, 0x1, 0x1)
        /home/flowers/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:336 +0x547
github.com/gilbertchen/duplicacy/src.CreateChunkDownloader.func1(0xc428712320, 0x4)                                                    /home/flowers/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:81 +0x161
created by github.com/gilbertchen/duplicacy/src.CreateChunkDownloader                                                                  /home/flowers/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:86 +0x23f
2017-09-20 14:15:00.139 ERROR UPLOAD_CHUNK Failed to decrypt the chunk 7153a420a3c53d4844b8ab2f3f82b5af7e0e4709af3916d2dae1e4e99459634c: cipher: message authentication failed
</pre>

This one does start with "duplicacy" but it couldn't be decrypted. This is making me think I must have messed up. I definitely did not manually upload any chunks to Wasabi, except as described above. But when I was trying to figure out how duplicacy works, I might have re-created the repository a few times on my machine and not wiped out what had already been uploaded to Wasabi. I think I thought it wouldn't matter because I thought the chunk hashes depended not only on the chunk contents but on the encryption key as well.

Regardless of how it happens though, it is not out of the question that a chunk could become corrupt due to bit rot. A single corrupt chunk should not prevent the restoration of all subsequent files that reside wholly inside valid chunks. If the corrupt chunk is encountered early it could make virtually the entire backup inaccessible.

Duplicacy should skip the files that are stored in the corrupt chunk and resume restoring files when it gets back into valid chunks. It should log the names of the files that could not be restored.

EDIT: I copied information for context from the duplicacy issue into here (between the horizontal rules).

**Comment by gilbertchen** [comment]
> I thought the chunk hashes depended not only on the chunk contents but on the encryption key as well.

The chunk names are dependent on both the contents and the id key.  Both the id key and the encryption key are stored in `config`, so if you are using the same config file it should decrypt even if the chunk was from the previously configured storage.  If the config files are different, then it is very unlikely that chunks will have the same name, unless there is a hash collision.

I don't know how you could get into this situation if this is not a Duplicacy or Wasabi bug.  The first chunk wasn't an unencrypted chunk because all unencrypted chunks should start with 'LZ4'.

I think what I can do is to add a -verify switch to the backup command, which will verify the chunk content after the chunk has been uploaded.

**Comment by tbain98** [comment]
So there are several times/places where corrupted content could occur:

1. Duplicacy corrupts content before upload.
2. Content is corrupted in transit during upload.
3. The storage provider corrupts content while holding it.
4, The storage provider transmits the wrong content during download.
5. Content is corrupted in transit during download.
6. Duplicacy corrupts content after download.

* For 1, the problem can be detected by decoding the content and confirming that it matches the content on the disk (don't trust whatever buffer you might have in memory that contains the raw content you actually read, because it could have been corrupted). I'd definitely like to have the option to do this, and I'm torn about whether this behavior should actually be the default behavior (I'm leaning towards "yes" in light of the behavior that @macdanny is describing, but could see both sides of the argument).
* For 2, S3 provides a way to verify that the content stored is the content that was transmitted; you transmit an MD5 checksum along with the request, and if the content doesn't produce the same MD5 checksum once S3 has received it, S3 returns an error. (See the Content-MD5 header described in http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html.) Presumably some (most?) other providers have a way to validate that the content was not corrupted in transit, and I think it's worth doing that as baseline functionality (don't make it an option, just make Duplicacy do it on every chunk, with no option to disable it). If no option is provided, handle as for 3.
* For 3, there's nothing you can do to prevent this, and nothing you can do to recover from it. You're screwed.
* For 4, you can compute the hash of the received content and verify that it matches the requested filename. If not, request the file again (up to some limit), hoping that the provider will send the correct content upon retry. This should be default behavior.
* For 5, if the storage provider transmits a checksum along with the content, you can compute the checksum yourself upon receipt to verify the integrity of the transmitted content. If not (S3 appears not to), handle as for 4.
* For 6, if it happens before the raw text is decoded, handle as for 4. After that, you can read the content back in from disk and confirm that it produces a hash that matches the requested filename. This should be default behavior.

So in light of all of that, I think we should:
1. Add the ability to decode the encoded content and re-read the raw content from disk, and make sure that they match. Confirm that the same hash (filename) is computed. Do this post-upload. I'm inclined to make this default behavior.
1. Add transmission/validation of a checksum as part of the upload and download requests for all storage providers who give that ability. Make this the only behavior (no option) when the storage provider supports it.
1. After receiving content from a storage provider, confirm that the content produces a hash that matches the requested filename, and re-request the content if not. Make this the only behavior (no option). Add code that will panic if we're failing too often (TBD on what "too often" actually means, but I agree with Danny that there should be the ability to skip some reasonable number of corrupted chunks but let the rest of the restore operation continue) to avoid wasting too much money downloading chunks if they're being correctly transmitted but are incorrect on the storage provider's disks.
1. After writing raw content to disk, read that content back in and compute the hash for the newly-read content. If it doesn't produce the correct hash, re-request the content and start over. Make this the only behavior (no option). Use the same don't-try-forever logic as above.

Duplicacy may already do some of these things; I haven't spent enough time looking at the code to be sure which ones exist and which don't. But I think the end goal should be to add whichever of these things we're not already doing.

**Comment by macdanny** [comment]
> 8. I downloaded the failing chunk from Wasabi and compared it to the chunk from the local storage. They are different. They are exactly the same size, but their contents are completely different.

I thought this meant something, but in fact, by itself it means nothing because a nonce is prepended to the chunk data prior to encryption. Since I re-created the chunks instead of copying them they are virtually guaranteed to all have entirely different contents.

I only want to clarify this for the record.

**Comment by skidvd** [comment]
I am curious if there has been any progress/plans with respect to the use of the MD5 checksum for ensuring the integrity of the source to storage exchange?
