### ISSUE TITLE
duplicacy info fails unless -repository option is specified

### ISSUE THREAD

**Issue by deekue** [gilbertchen/duplicacy#210]
-repository isn't really an option if it's required for the command to work.

duplicacy is dumping a stack trace even though I didn't specify the -stack global option

```
$ ls -d .duplicacy
.duplicacy
$ duplicacy info -e sftp://user@host//usr/local/backup
The preference path has not been set
panic: (duplicacy.Exception) (0xc98be0,0xc42018e810)

goroutine 50 [running]:
github.com/gilbertchen/duplicacy/src.logf(0x2, 0xd4a2b2, 0xf, 0xd5e431, 0x24, 0x0, 0x0, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:160 +0x1bc
github.com/gilbertchen/duplicacy/src.LOG_ERROR(0xd4a2b2, 0xf, 0xd5e431, 0x24, 0x0, 0x0, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:98 +0x73
github.com/gilbertchen/duplicacy/src.GetDuplicacyPreferencePath(0x101, 0xc4202be200)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_preference.go:81 +0x7d
github.com/gilbertchen/duplicacy/src.checkHostKey(0xc420258bc0, 0x19, 0x11535a0, 0xc42018e5d0, 0x11566a0, 0xc4201911a0, 0x0, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_storage.go:80 +0x4f
github.com/gilbertchen/duplicacy/src.CreateStorage.func4(0xc420258bc0, 0x19, 0x11535a0, 0xc42018e5d0, 0x11566a0, 0xc4201911a0, 0x0, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_storage.go:312 +0x5d
golang.org/x/crypto/ssh.(*handshakeTransport).client(0xc4201ac160, 0x1152960, 0x11bdc78, 0xc4201a8900, 0xc4201b04e0, 0x1, 0x0, 0xc420023300)
	/Users/chgang/zincbox/go/src/golang.org/x/crypto/ssh/handshake.go:634 +0x188
golang.org/x/crypto/ssh.(*handshakeTransport).enterKeyExchange(0xc4201ac160, 0xc42005b000, 0x38b, 0x38b, 0x1, 0x30)
	/Users/chgang/zincbox/go/src/golang.org/x/crypto/ssh/handshake.go:580 +0x64a
golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc4201ac160)
	/Users/chgang/zincbox/go/src/golang.org/x/crypto/ssh/handshake.go:295 +0x1ec
created by golang.org/x/crypto/ssh.newClientTransport
	/Users/chgang/zincbox/go/src/golang.org/x/crypto/ssh/handshake.go:129 +0x1a5
$ duplicacy info -e -repository $HOME sftp://user@host//usr/local/backup
Failed to read the private key file: open use ssh agent: no such file or directory
Compression level: 100
Average chunk size: 4194304
Maximum chunk size: 16777216
Minimum chunk size: 1048576
Chunk seed: ???????
```

**Comment by gilbertchen** [comment]
Fixed by https://github.com/gilbertchen/duplicacy/commit/80742ce2ba349c74e534613dbcc2604085cc9bcd.
