### ISSUE TITLE
Runtime error: invalid memory address during duplicacy add

### ISSUE THREAD

**Issue by adrinux** [gilbertchen/duplicacy#251]
Attempting to add a second storage I get this error.
Running on ubuntu 17.10, happens with both duplicacy_linux_x64_2.0.9 release and a fresh go get build
```
$ duplicacy add -copy -encrypt newstorage-id repo-id b2://bucket0name                           
Enter Backblaze Account ID:------------------
Enter Backblaze Application Key:-----------------------------------------------
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x41, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
	/home/adrian/Admin/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:183 +0x1ad
panic(0xc68ca0, 0x1235fd0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
main.configRepository(0xc42018cb40, 0xc42018cb00)
	/home/adrian/Admin/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:378 +0x997
main.addStorage(0xc42018cb40)
	/home/adrian/Admin/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:195 +0x30
github.com/gilbertchen/cli.Command.Run(0xd706a6, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd9e221, 0x40, 0x0, ...)
	/home/adrian/Admin/go/src/github.com/gilbertchen/cli/command.go:160 +0x827
github.com/gilbertchen/cli.(*App).Run(0xc42018c900, 0xc420096000, 0x7, 0x7, 0x0, 0x0)
	/home/adrian/Admin/go/src/github.com/gilbertchen/cli/app.go:179 +0x8c1
main.main()
	/home/adrian/Admin/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:1739 +0x49d0

```

**Comment by gilbertchen** [comment]
The '-copy' option is followed by the name to the storage with which the new storage will be compatible.  What you want is perhaps:

```
$ duplicacy add -copy default -encrypt newstorage-id repo-id b2://bucket0name   
```

But of course this shouldn't cause a crash.  I'll take a look at why.

**Comment by adrinux** [comment]
Just tried on an OSX box, yes, you're right on both counts. Works ok if I specify the storage name to copy.
