### ISSUE TITLE
503 "Slow Down" error in s3c (digital ocean)

### ISSUE THREAD

**Issue by genevera** [gilbertchen/duplicacy#316]
I noticed that duplicacy doesn't seem to handle 503s very well for an s3c backend (in my case, digital ocean):

```bash
2017-12-27 23:55:56.010 DEBUG CHUNK_UPLOAD Chunk 9c18684f2917f6d91b0558c642514336df7c06618678ed53a70d179c6ce69702 has been uploaded
2017-12-27 23:55:56.010 INFO UPLOAD_PROGRESS Uploaded chunk 445 size 3319573, 13.15MB/s 02:08:53 2.1%
2017-12-27 23:55:56.786 DEBUG CHUNK_UPLOAD Chunk 2d39609665f14aa917cbc477c1738533080c0e3754c98ba76bfc127ba111a321 has been uploaded
2017-12-27 23:55:56.786 INFO UPLOAD_PROGRESS Uploaded chunk 446 size 9249826, 13.20MB/s 02:08:22 2.1%
955380-2017-12-27 23:55:58.442 DEBUG CHUNK_UPLOAD Chunk 14c261e36ccc95b859bd3de5cfd8f7d62959b4ef68487e4dd5ea9adfaf3cfafc has been uploaded
2017-12-27 23:55:58.442 INFO UPLOAD_PROGRESS Uploaded chunk 447 size 14087874, 13.13MB/s 02:09:05 2.1%
2017-12-27 23:55:58.869 DEBUG CHUNK_UPLOAD Chunk f3fb977b5a6e471abdee230a9abcd7afd1a9139206da59d40275444b0f54b2b1 has been uploaded
2017-12-27 23:55:58.869 INFO UPLOAD_PROGRESS Uploaded chunk 448 size 3196696, 13.14MB/s 02:08:54 2.2%
955384:2017-12-27 23:55:59.389 ERROR UPLOAD_CHUNK Failed to upload the chunk 89c39e6168daefca2d759a00bfac1f00e826fe8281611cd1e5659b49ee3106c0: 503 Slow Down
goroutine 27 [running]:
runtime/debug.Stack(0x96, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x22
955390-github.com/gilbertchen/duplicacy/src.CatchLogException()
	/Users/genevera/src/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:177 +0x13d
panic(0x48e0fa0, 0xc428e01710)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/gilbertchen/duplicacy/src.logf(0x2, 0x4999682, 0xc, 0x49ac2d8, 0x21, 0xc420539e48, 0x2, 0x2)
	/Users/genevera/src/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:156 +0x8da
github.com/gilbertchen/duplicacy/src.LOG_ERROR(0x4999682, 0xc, 0x49ac2d8, 0x21, 0xc420539e48, 0x2, 0x2)
	/Users/genevera/src/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:98 +0x73
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Upload(0xc42ab7c050, 0x1, 0xc423c020a0, 0x1c2, 0x1)
	/Users/genevera/src/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:140 +0x565
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start.func1(0xc42ab7c050, 0x1)
 /Users/genevera/src/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:60 +0x83
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
 +0x48
2017-12-27 23:55:59.499 INFO INCOMPLETE_SAVE Incomplete snapshot saved to /Users/genevera/.duplicacy/incomplete
```

**Comment by gilbertchen** [comment]
Can you try the s3 backend?  The s3c backend was mainly for s3-compatible providers that doesn't support V4 signature but I remember digital ocean should support V4 and thus works with the s3 backend.

**Comment by giphyvera** [comment]
S3 backend worked like a charm.  Thank you! I was using s3c because I noticed that it was using s3c in the tests.

**Comment by genevera** [comment]
S3 backend worked like a charm. Thank you! I was using s3c because I noticed that it was using s3c in the tests.

**Comment by genevera** [comment]
Closing because it's not an issue.
