### ISSUE TITLE
`history -hash` for excluded file = `runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by gboudreau** [gilbertchen/duplicacy#430]
```
$ duplicacy -background history -hash -r 162 Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2
Storage set to sftp://gb@fileserver3//mnt/hdd5/backups/duplicacy/Guillaumes-MacBook-Pro-gb-gb/
Failed to parse the private key file /Users/gb/.ssh/id_ed25519: ssh: cannot decode encrypted private keys
    162:
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x41, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:183 +0x1ad
panic(0x48cc200, 0x4ecde70)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).ShowHistory(0xc420308030, 0xc420018054, 0x9, 0xc4201cd760, 0x1c, 0xc42032a220, 0x1, 0x1, 0x7ffeefbff62b, 0x3c, ...)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:1487 +0xb16
main.showHistory(0xc420180d80)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:1031 +0x4a1
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.Command.Run(0x49de253, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x49f0ece, 0x1a, 0x0, ...)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/command.go:160 +0x8bc
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.(*App).Run(0xc420180b40, 0xc4200100e0, 0x7, 0x7, 0x0, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/app.go:179 +0x8e3
main.main()
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:1860 +0x513c
```

It works fine without `-hash`:
```
$ duplicacy -background history -r 162 Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2
Storage set to sftp://gb@fileserver3//mnt/hdd5/backups/duplicacy/Guillaumes-MacBook-Pro-gb-gb/
Failed to parse the private key file /Users/gb/.ssh/id_ed25519: ssh: cannot decode encrypted private keys
    162:
current:     26271547392 2018-05-28 15:34:45                                                                  Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2
```

or when using a file that doesn't exist:
```
$ duplicacy -background history -hash -r 162 patate-123
Storage set to sftp://gb@fileserver3//mnt/hdd5/backups/duplicacy/Guillaumes-MacBook-Pro-gb-gb/
Failed to parse the private key file /Users/gb/.ssh/id_ed25519: ssh: cannot decode encrypted private keys
    162:
current:
```

**Comment by gilbertchen** [comment]
Fixed by https://github.com/gilbertchen/duplicacy/commit/0e585e4be4e4e6a61ab2e1ebf591105c3bb060d0
