### ISSUE TITLE
Unable to add Google Drive storage to the repository

### ISSUE THREAD

**Issue by kaharlichenko** [gilbertchen/duplicacy#464]
I'm trying to add a Google Drive storage to an already initialized repo.

The documentation doesn't really tell what to use instead of `gcd://path/to/storage`, I assume I could put the path relative to my Google Drive root.

I've downloaded the `gcd-token.json` file, then run this command:

```
duplicacy -d -log -stack add google-disk projects gcd://duplicacy
2018-07-22 15:08:46.074 DEBUG PASSWORD_ENV_VAR Reading the environment variable DUPLICACY_GOOGLE-DISK_GCD_TOKEN
Enter the path of the Google Drive token file (downloadable from https://duplicacy.com/gcd_start):/path/to/gcd-token.json
2018-07-22 15:08:48.693 ERROR STORAGE_CREATE Failed to load the Google Drive storage at gcd://duplicacy: Failed to create directory 'duplicacy': Parent directory '' does not exist
```

Here's the trace:

```
goroutine 1 [running]:
runtime/debug.Stack(0xb4, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:177 +0x13d
panic(0xd45600, 0xc4203862a0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/gilbertchen/duplicacy/src.logf(0x2, 0xe06aeb, 0xe, 0xe2794a, 0x31, 0xc4204cf330, 0x2, 0x2)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:160 +0x1bc
github.com/gilbertchen/duplicacy/src.LOG_ERROR(0xe06aeb, 0xe, 0xe2794a, 0x31, 0xc4204cf330, 0x2, 0x2)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:98 +0x73
github.com/gilbertchen/duplicacy/src.CreateStorage(0x7ffc48116d91, 0xb, 0x7ffc48116d9d, 0x8, 0x7ffc48116da6, 0xf, 0x0, 0x0, 0x4d00000000000001, 0x1, ...)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_storage.go:536 +0x3176
main.configRepository(0xc4201d90e0, 0xc4201d9000)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:303 +0x56b
main.addStorage(0xc4201d90e0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:207 +0x30
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.Command.Run(0xdfc12c, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2e2ae, 0x40, 0x0, ...)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/command.go:160 +0x8bc
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.(*App).Run(0xc4201d8ea0, 0xc42000e200, 0x8, 0x8, 0x0, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/app.go:179 +0x8e3
main.main()
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:1860 +0x513c

```

I'm running Ubuntu 16.04, duplicacy_linux_x64_2.1.0.

**Comment by droolio** [comment]
Did you create the /duplicacy directory on the root of your Google Drive?

**Comment by kaharlichenko** [comment]
Hm, this kind of obvious solution didn't come to my mind. I created the base directory manually and now it does work.

Maybe it is a good idea to add a little bit more documentation on how to set up your storage backends just to avoid such questions in future?

**Comment by TheBestPessimist** [comment]
Added to:
https://github.com/gilbertchen/duplicacy/wiki/Quick-Start
and 
https://github.com/gilbertchen/duplicacy/wiki/init
