### ISSUE TITLE
Pruning crashes on 2.1.1

### ISSUE THREAD

**Issue by nriley** [gilbertchen/duplicacy#469]
Pruning has started crashing since I upgraded from 2.1.0 to 2.1.1 (Linux 32-bit), even if I just run in dry-run mode:

```
# duplicacy prune -d
Storage set to sftp://[...]
No snapshot to delete
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x41, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x8a
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1a
github.com/gilbertchen/duplicacy/src.CatchLogException()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:183 +0x110
panic(0x877c4a0, 0x8ceee38)
        /usr/local/go/src/runtime/panic.go:502 +0x1dc
sync/atomic.LoadUint64(0x1a523904, 0xc, 0x1a4000e0)
        /usr/local/go/src/sync/atomic/asm_386.s:159 +0xb
github.com/gilbertchen/duplicacy/src.(*ChunkOperator).Stop(0x1a5238f0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkoperator.go:72 +0x2e
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).PruneSnapshots(0x1a664460, 0x1a4825f8, 0x5, 0x1a4825f8, 0x5, 0x0, 0x0, 0x0, 0x8d0c6e8, 0x0, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:1920 +0x3efd
main.pruneSnapshots(0x1a47c870)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:1117 +0x65a
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.Command.Run(0x883bd45, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8867187, 0x35, 0x0, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/command.go:160 +0x6d0
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.(*App).Run(0x1a424c80, 0x1a46e0e0, 0x3, 0x4, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/app.go:179 +0x6df
main.main()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2007 +0x444e
```

No problems if I go back to 2.1.0:

```
# duplicacy prune -d
Storage set to sftp://[...]
No snapshot to delete
```

Please let me know if there's any other info that is helpful to track this down.

**Comment by gilbertchen** [comment]
This is caused by the mis-alignment of 64 bit atomic integers on 32bit cpu.  Fixed by https://github.com/gilbertchen/duplicacy/commit/fce42348617039134300101a54af4990aa7d6c3c and included in the updated 2.1.1 release.

**Comment by nriley** [comment]
Redownloaded 2.1.1 and it is no longer crashing on prune. Thanks for the quick fix.

**Comment by gilbertchen** [comment]
This issue has been mentioned on **Duplicacy Forum**. There might be relevant details there:

https://forum.duplicacy.com/t/cli-2-7-0-crashes-when-running-check-on-32-bit-cpu/4274/5
