### ISSUE TITLE
"check" crashes

### ISSUE THREAD

**Issue by Fonant** [gilbertchen/duplicacy#483]
Command: `duplicacy -v -log check -all -fossils -resurrect`

Result on one storage copy:

```
...
2018-08-14 11:17:14.944 INFO SNAPSHOT_CHECK All chunks referenced by snapshot arthur at revision 1842 exist
2018-08-14 11:17:14.945 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/arthur/1843 from the snapshot cache
2018-08-14 11:17:14.945 DEBUG DOWNLOAD_FETCH Fetching chunk d8e0cc146113dd61ed950006cf92d7beab1f1c13bef09434aa1cbe45ff124498
2018-08-14 11:17:14.945 DEBUG CHUNK_CACHE Chunk d8e0cc146113dd61ed950006cf92d7beab1f1c13bef09434aa1cbe45ff124498 has been loaded from the snapshot cache
2018-08-14 11:17:14.949 INFO SNAPSHOT_CHECK All chunks referenced by snapshot arthur at revision 1843 exist
2018-08-14 11:17:14.950 DEBUG DOWNLOAD_FILE_CACHE Loaded file snapshots/arthur/1844 from the snapshot cache
2018-08-14 11:17:14.950 DEBUG DOWNLOAD_FETCH Fetching chunk c5ece319bb7eb6416e5cb8227b2a1df61734747a81f190471f7818b3e8aed569
2018-08-14 11:17:14.950 DEBUG CHUNK_CACHE Chunk c5ece319bb7eb6416e5cb8227b2a1df61734747a81f190471f7818b3e8aed569 has been loaded from the snapshot cache
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x41, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:183 +0x189
panic(0xc61720, 0x12c4950)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/gilbertchen/duplicacy/src.(*ChunkOperator).AddTask(...)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkoperator.go:94
github.com/gilbertchen/duplicacy/src.(*ChunkOperator).Resurrect(...)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkoperator.go:111
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).resurrectChunk(0xc420072240, 0xc421a525f0, 0x4d, 0xc4223199c0, 0x40, 0xc421a525f0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:1521 +0xe1
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).CheckSnapshots(0xc420072240, 0xc42216b5f0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x101000000, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:851 +0xf41
main.checkSnapshots(0xc4202e4120)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:913 +0x58b
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.Command.Run(0xd7af4f, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd94790, 0x20, 0x0, ...)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/command.go:160 +0x7ea
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.(*App).Run(0xc4201b3680, 0xc42002e070, 0x7, 0x7, 0x0, 0x0)
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/app.go:179 +0x864
main.main()
	/Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2007 +0x57ab
```

Is there any more info I can provide to help debug?

**Comment by gilbertchen** [comment]
This was fixed by https://github.com/gilbertchen/duplicacy/commit/f304b64b3f607a61bdda9e3ece74fe6b022fb6ec.  After this commit I redid the 2.1.1 release, so if you download the binary from the releases page, the new binary should contain this fix.

**Comment by Fonant** [comment]
Ah, OK, thanks!
