### ISSUE TITLE
Crash during initial upload to Google Drive

### ISSUE THREAD

**Issue by gboudreau** [gilbertchen/duplicacy#491]
```
$ uname -a
Linux fileserver3 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 GNU/Linux

$ cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ duplicacy
[...]
VERSION:
   2.1.1
[...]

# duplicacy init -encrypt fileserver3-all gcd://duplicacy-backups
[...]

# duplicacy -log backup -stats -threads 4 -hash
2018-09-10 20:10:35.758 INFO STORAGE_SET Storage set to gcd://duplicacy-backups
2018-09-10 20:10:39.137 INFO BACKUP_START No previous backup found
2018-09-10 20:10:39.137 INFO BACKUP_INDEXING Indexing /mnt/hdd5/backups/duplicacy-to-backup
2018-09-10 20:10:39.138 INFO SNAPSHOT_FILTER Loaded 6 include/exclude pattern(s)
[...]
2018-09-11 00:13:05.768 INFO UPLOAD_PROGRESS Uploaded chunk 15452 size 3441110, 6.08MB/s 3 days 10:36:41 3.9%
2018-09-11 00:13:05.868 INFO UPLOAD_PROGRESS Uploaded chunk 15453 size 1183863, 6.08MB/s 3 days 10:36:37 3.9%
2018-09-11 00:13:10.293 INFO UPLOAD_PROGRESS Uploaded chunk 15457 size 3711560, 6.08MB/s 3 days 10:38:23 3.9%
2018-09-11 00:13:11.150 INFO UPLOAD_PROGRESS Uploaded chunk 15454 size 14403134, 6.08MB/s 3 days 10:37:50 3.9%
2018-09-11 00:13:11.392 INFO UPLOAD_PROGRESS Uploaded chunk 15456 size 9721735, 6.08MB/s 3 days 10:37:12 3.9%
2018-09-11 00:13:11.555 INFO UPLOAD_PROGRESS Uploaded chunk 15455 size 5696949, 6.08MB/s 3 days 10:36:49 3.9%
2018-09-11 00:13:11.952 INFO UPLOAD_PROGRESS Uploaded chunk 15458 size 4227506, 6.08MB/s 3 days 10:36:33 3.9%
unexpected fault address 0xfffffffff0457400
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfffffffff0457400 pc=0xfffffffff0457400]

goroutine 70046 [running]:
runtime.throw(0xd7b080, 0x5)
        /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc4374689b0 sp=0xc437468990 pc=0x42ac41
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:395 +0x211 fp=0xc437468a00 sp=0xc4374689b0 pc=0x440451
internal/poll.(*FD).Write(0xc440087900, 0xc4351a2000, 0x1e, 0x8000, 0x9, 0x7ffb, 0xc43de965a0)
        /usr/local/go/src/internal/poll/fd_unix.go:242 +0x37a fp=0xc437468a08 sp=0xc437468a00 pc=0x4c6b9a
net.(*netFD).Write(0xc440087900, 0xc4351a2000, 0x1e, 0x8000, 0x40d16d, 0x9, 0xc94840)
        /usr/local/go/src/net/fd_unix.go:220 +0x4f fp=0xc437468a68 sp=0xc437468a08 pc=0x5b7bef
net.(*conn).Write(0xc420344528, 0xc4351a2000, 0x1e, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:188 +0x6a fp=0xc437468ac8 sp=0xc437468a68 pc=0x5c8c5a
crypto/tls.(*Conn).write(0xc43de96380, 0xc4351a2000, 0x1e, 0x8000, 0xc42045cca0, 0x1, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:854 +0x191 fp=0xc437468b38 sp=0xc437468ac8 pc=0x617ea1
crypto/tls.(*Conn).writeRecordLocked(0xc43de96380, 0xdb6f17, 0xc420029000, 0x4009, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:931 +0x352 fp=0xc437468bc8 sp=0xc437468b38 pc=0x618362
crypto/tls.(*Conn).Write(0xc43de96380, 0xc420025000, 0x4009, 0x4800, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1090 +0x188 fp=0xc437468c30 sp=0xc437468bc8 pc=0x619118
net/http.http2stickyErrWriter.Write(0x7fa5e875ca50, 0xc43de96380, 0xc420272f98, 0xc420025000, 0x4009, 0x4800, 0x3, 0xc437468d40, 0x459d74)
        /usr/local/go/src/net/http/h2_bundle.go:6854 +0x71 fp=0xc437468c80 sp=0xc437468c30 pc=0x695281
net/http.(*http2stickyErrWriter).Write(0xc4200c9760, 0xc420025000, 0x4009, 0x4800, 0xc437468d40, 0xc437468d88, 0x459d74)
        <autogenerated>:1 +0x74 fp=0xc437468cd8 sp=0xc437468c80 pc=0x6dbbf4
bufio.(*Writer).Write(0xc4200b6ec0, 0xc420025000, 0x4009, 0x4800, 0x0, 0xc437468d80, 0x1)
        /usr/local/go/src/bufio/bufio.go:605 +0x14d fp=0xc437468d40 sp=0xc437468cd8 pc=0x57286d
net/http.(*http2Framer).endWrite(0xc4200120e0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1646 +0xad fp=0xc437468d98 sp=0xc437468d40 pc=0x67d65d
net/http.(*http2Framer).WriteDataPadded(0xc4200120e0, 0x23c3, 0xc43be94000, 0x4000, 0x4000, 0x0, 0x0, 0x0, 0xc420272e00, 0xc420272e50)
        /usr/local/go/src/net/http/h2_bundle.go:1968 +0x289 fp=0xc437468e10 sp=0xc437468d98 pc=0x67eff9
net/http.(*http2Framer).WriteData(0xc4200120e0, 0x23c3, 0xc43be94000, 0x4000, 0x4000, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1926 +0x72 fp=0xc437468e70 sp=0xc437468e10 pc=0x67ed42
net/http.(*http2clientStream).writeRequestBody(0xc426fdf7c0, 0x7fa5e7924108, 0xc4200ccaa0, 0x7fa5e7924128, 0xc4200ccaa0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:7623 +0x2f8 fp=0xc437468f68 sp=0xc437468e70 pc=0x69a268
net/http.(*http2Transport).getBodyWriterState.func1()
        /usr/local/go/src/net/http/h2_bundle.go:8794 +0xc2 fp=0xc437468fe0 sp=0xc437468f68 pc=0x6ce4a2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc437468fe8 sp=0xc437468fe0 pc=0x459cb1
created by net/http.http2bodyWriterState.scheduleBodyWrite
        /usr/local/go/src/net/http/h2_bundle.go:8841 +0x8e

goroutine 1 [runnable]:
github.com/gilbertchen/duplicacy/src.(*ChunkMaker).ForEachChunk.func2(0x100000)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkmaker.go:123 +0x1c2
github.com/gilbertchen/duplicacy/src.(*ChunkMaker).ForEachChunk(0xc43ea36000, 0xe4be20, 0xc4200b0138, 0xc42adfb540, 0xc42adfb3b8)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkmaker.go:279 +0x734
github.com/gilbertchen/duplicacy/src.(*BackupManager).Backup(0xc4200b2140, 0xc420034034, 0x25, 0x0, 0x4, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_backupmanager.go:497 +0x3b65
main.backupRepository(0xc420286120)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:724 +0x5b1
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.Command.Run(0xd7bd3a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xda327e, 0x30, 0x0, ...)                
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/command.go:160 +0x7ea
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.(*App).Run(0xc4201d8b40, 0xc4200b4000, 0x7, 0x7, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/app.go:179 +0x864
main.main()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2007 +0x57ab

goroutine 19 [syscall, 236 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 3 [chan receive, 236 minutes]:
main.main.func1(0xc420097b00)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2001 +0x60
created by main.main
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2000 +0x5779

goroutine 21 [select, 236 minutes, locked to thread]:
runtime.gopark(0xdb6de0, 0x0, 0xd7c66a, 0x6, 0x18, 0x1)  
        /usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42004a750, 0xc420098420)
        /usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 46 [select]:
net/http.(*http2ClientConn).roundTrip(0xc420272e00, 0xc4263b4700, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:7442 +0x844
net/http.(*http2Transport).RoundTripOpt(0xc420170280, 0xc4263b4700, 0xffffffffffffff00, 0x0, 0x40a3e0, 0xd7b134)
        /usr/local/go/src/net/http/h2_bundle.go:6929 +0x150
net/http.(*http2Transport).RoundTrip(0xc420170280, 0xc4263b4700, 0xc445ec6e60, 0x0, 0xc445ec6dd8)
        /usr/local/go/src/net/http/h2_bundle.go:6891 +0x3a
net/http.http2noDialH2RoundTripper.RoundTrip(0xc420170280, 0xc4263b4700, 0xc443dd5c20, 0x5, 0xc420286628)
        /usr/local/go/src/net/http/h2_bundle.go:991 +0x39
net/http.(*Transport).RoundTrip(0x12ce0a0, 0xc4263b4700, 0xc4263b4700, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/net/http/transport.go:380 +0xc36
github.com/gilbertchen/duplicacy/vendor/golang.org/x/oauth2.(*Transport).RoundTrip(0xc42016c6f0, 0xc4263b4600, 0xc42016c6f0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/golang.org/x/oauth2/transport.go:48 +0xcf
net/http.send(0xc4263b4600, 0xe4b2c0, 0xc42016c6f0, 0x0, 0x0, 0x0, 0xc42000c818, 0xf, 0xc43ecaf6d8, 0x1)
        /usr/local/go/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc42016c720, 0xc4263b4600, 0x0, 0x0, 0x0, 0xc42000c818, 0x0, 0x1, 0x100)
        /usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc42016c720, 0xc4263b4600, 0xd83f26, 0xf, 0x12f8cc0)
        /usr/local/go/src/net/http/client.go:615 +0x28d
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport.SendRequest(0x0, 0x0, 0xc42016c720, 0xc4263b4600, 0x0, 0x0, 0xc4263b4600)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport/send.go:43 +0x254
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3.(*FilesListCall).doRequest(0xc43ecafb18, 0xd7a603, 0x4, 0x0, 0x1f, 0xd93d9b)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3/drive-gen.go:5106 +0x37b
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3.(*FilesListCall).Do(0xc43ecafb18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3/drive-gen.go:5118 +0x85
github.com/gilbertchen/duplicacy/src.(*GCDStorage).listByName(0xc4202b8000, 0x0, 0xc44577ec60, 0x21, 0xc42f488e1a, 0x3e, 0x21, 0x0, 0x0, 0xc42f488e1a, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_gcdstorage.go:218 +0x25d
github.com/gilbertchen/duplicacy/src.(*GCDStorage).GetFileInfo(0xc4202b8000, 0x0, 0xc42f488e10, 0x48, 0x3e, 0xc42f488e10, 0x48, 0xc42c6250b0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_gcdstorage.go:605 +0x24c
github.com/gilbertchen/duplicacy/src.(*StorageBase).FindChunk(0xc4202b8000, 0x0, 0xc4252e5740, 0x40, 0x404600, 0x0, 0x0, 0xc42adfaa00, 0x0, 0x0, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_storage.go:151 +0x1c4
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Upload(0xc43e4be280, 0x0, 0xc43e4be500, 0x3c66, 0x1)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:115 +0xcf
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start.func1(0xc43e4be280, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:60 +0x83
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:55 +0x48

goroutine 47 [select]:
net/http.(*http2ClientConn).roundTrip(0xc420272e00, 0xc4263b4500, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:7442 +0x844
net/http.(*http2Transport).RoundTripOpt(0xc420170280, 0xc4263b4500, 0xffffffffffffff00, 0x0, 0x40a3e0, 0xd7b134)
        /usr/local/go/src/net/http/h2_bundle.go:6929 +0x150
net/http.(*http2Transport).RoundTrip(0xc420170280, 0xc4263b4500, 0xc445ec6620, 0x0, 0xc445ec6598)
        /usr/local/go/src/net/http/h2_bundle.go:6891 +0x3a
net/http.http2noDialH2RoundTripper.RoundTrip(0xc420170280, 0xc4263b4500, 0xc43a548b40, 0x5, 0xc420286628)
        /usr/local/go/src/net/http/h2_bundle.go:991 +0x39
net/http.(*Transport).RoundTrip(0x12ce0a0, 0xc4263b4500, 0xc4263b4500, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/net/http/transport.go:380 +0xc36
github.com/gilbertchen/duplicacy/vendor/golang.org/x/oauth2.(*Transport).RoundTrip(0xc42016c6f0, 0xc4263b4400, 0xc42016c6f0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/golang.org/x/oauth2/transport.go:48 +0xcf
net/http.send(0xc4263b4400, 0xe4b2c0, 0xc42016c6f0, 0x0, 0x0, 0x0, 0xc42000c7e8, 0x16, 0xc43ecad828, 0x1)
        /usr/local/go/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc42016c720, 0xc4263b4400, 0x0, 0x0, 0x0, 0xc42000c7e8, 0x0, 0x1, 0x100)
        /usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc42016c720, 0xc4263b4400, 0xd83f26, 0xf, 0x12f8cc0)
        /usr/local/go/src/net/http/client.go:615 +0x28d
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport.SendRequest(0x0, 0x0, 0xc42016c720, 0xc4263b4400, 0x7fa5e7924108, 0xc4200ccaa0, 0xc4263
b4400)  
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport/send.go:43 +0x254
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3.(*FilesCreateCall).doRequest(0xc43ecadc78, 0xd7a603, 0x4, 0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3/drive-gen.go:4149 +0x4c6
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3.(*FilesCreateCall).Do(0xc43ecadc78, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3/drive-gen.go:4161 +0x8b
github.com/gilbertchen/duplicacy/src.(*GCDStorage).UploadFile(0xc4202b8000, 0x1, 0xc4374a81e0, 0x48, 0xc44d320000, 0x2f1fda, 0x3008315, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_gcdstorage.go:666 +0x3a7
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Upload(0xc43e4be280, 0x1, 0xc43e4be4b0, 0x3c64, 0x1)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:138 +0x417
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start.func1(0xc43e4be280, 0x1)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:60 +0x83
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:55 +0x48

goroutine 48 [running]:
        goroutine running on other thread; stack unavailable
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:55 +0x48

goroutine 81 [select]:
net/http.(*http2ClientConn).roundTrip(0xc420272e00, 0xc437bee800, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:7442 +0x844
net/http.(*http2Transport).RoundTripOpt(0xc420170280, 0xc437bee800, 0xffffffffffffff00, 0x0, 0x40a3e0, 0xd7b134)
        /usr/local/go/src/net/http/h2_bundle.go:6929 +0x150
net/http.(*http2Transport).RoundTrip(0xc420170280, 0xc437bee800, 0xc4268d08f8, 0x0, 0xc4268d0868)
        /usr/local/go/src/net/http/h2_bundle.go:6891 +0x3a
net/http.http2noDialH2RoundTripper.RoundTrip(0xc420170280, 0xc437bee800, 0xc4426c0f00, 0x5, 0xc420286628)
        /usr/local/go/src/net/http/h2_bundle.go:991 +0x39
net/http.(*Transport).RoundTrip(0x12ce0a0, 0xc437bee800, 0xc437bee800, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/net/http/transport.go:380 +0xc36
github.com/gilbertchen/duplicacy/vendor/golang.org/x/oauth2.(*Transport).RoundTrip(0xc42016c6f0, 0xc437bee700, 0xc42016c6f0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/golang.org/x/oauth2/transport.go:48 +0xcf
net/http.send(0xc437bee700, 0xe4b2c0, 0xc42016c6f0, 0x0, 0x0, 0x0, 0xc4203446c8, 0x16, 0xc43eca9828, 0x1)
        /usr/local/go/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc42016c720, 0xc437bee700, 0x0, 0x0, 0x0, 0xc4203446c8, 0x0, 0x1, 0x100)
        /usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc42016c720, 0xc437bee700, 0xd83f26, 0xf, 0x12f8cc0)
        /usr/local/go/src/net/http/client.go:615 +0x28d
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport.SendRequest(0x0, 0x0, 0xc42016c720, 0xc437bee700, 0x7fa5e7924108, 0xc42047f840, 0xc437bee700)  
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport/send.go:43 +0x254
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3.(*FilesCreateCall).doRequest(0xc43eca9c78, 0xd7a603, 0x4, 0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3/drive-gen.go:4149 +0x4c6
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3.(*FilesCreateCall).Do(0xc43eca9c78, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/drive/v3/drive-gen.go:4161 +0x8b
github.com/gilbertchen/duplicacy/src.(*GCDStorage).UploadFile(0xc4202b8000, 0x3, 0xc4364a79a0, 0x48, 0xc45cd86000, 0x1796d8, 0x1f745f3, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_gcdstorage.go:666 +0x3a7
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Upload(0xc43e4be280, 0x3, 0xc437f1a000, 0x3c63, 0x1)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:138 +0x417
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start.func1(0xc43e4be280, 0x3)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:60 +0x83
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:55 +0x48

goroutine 70045 [select]:
io.(*pipe).Write(0xc4204345a0, 0xc47eefc000, 0x185fda, 0x694000, 0x16c000, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:87 +0x1e3
io.(*PipeWriter).Write(0xc42000c7c8, 0xc47ed90000, 0x2f1fda, 0x800000, 0x1, 0x1, 0xc)
        /usr/local/go/src/io/pipe.go:153 +0x4c
mime/multipart.(*part).Write(0xc4200ccbc0, 0xc47ed90000, 0x2f1fda, 0x800000, 0xc6fa80, 0xd10aa0, 0xc42044a701)
        /usr/local/go/src/mime/multipart/writer.go:190 +0xc3
bytes.(*Reader).WriteTo(0xc42af713e0, 0xe4b960, 0xc4200ccbc0, 0x7fa5e7924148, 0xc42af713e0, 0x1)
        /usr/local/go/src/bytes/reader.go:140 +0xa1
io.copyBuffer(0xe4b960, 0xc4200ccbc0, 0xe4aa80, 0xc42af713e0, 0x0, 0x0, 0x0, 0x1000100, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/io/io.go:382 +0x369
io.Copy(0xe4b960, 0xc4200ccbc0, 0xe4aa80, 0xc42af713e0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:362 +0x5a
github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport.newMultipartReader.func1(0xc42e6a7b80, 0x2, 0x2, 0xc42af71410, 0xc42000c7c8)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport/media.go:128 +0xe9
created by github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport.newMultipartReader
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/google.golang.org/api/gensupport/media.go:120 +0x232

goroutine 61275 [IO wait]:
internal/poll.runtime_pollWait(0x7fa5e88fbe30, 0x72, 0xc429345858)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc440087918, 0x72, 0xffffffffffffff00, 0xe4d160, 0x1285510)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc440087918, 0xc4203ab800, 0x400, 0x400)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc440087900, 0xc4203ab800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc440087900, 0xc4203ab800, 0x400, 0x400, 0x0, 0x8, 0x3fb)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc420344528, 0xc4203ab800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc4205192f0, 0x7fa5e8717040, 0xc420344528, 0x5, 0xc420344528, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:493 +0x96   
crypto/tls.(*Conn).readRecord(0xc43de96380, 0xdb6f17, 0xc43de964a0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc43de96380, 0xc4237af000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc420280f60, 0xc420012118, 0x9, 0x9, 0x100000000000009, 0x0, 0x10)
        /usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0xe4aa00, 0xc420280f60, 0xc420012118, 0x9, 0x9, 0x9, 0x429c0b, 0x10, 0xce74e0)
        /usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0xe4aa00, 0xc420280f60, 0xc420012118, 0x9, 0x9, 0xc42003a070, 0xc42003a000, 0xc428d82c18)
        /usr/local/go/src/io/io.go:327 +0x58
net/http.http2readFrameHeader(0xc420012118, 0x9, 0x9, 0xe4aa00, 0xc420280f60, 0x0, 0x0, 0x1c6, 0xc429345dc0)
        /usr/local/go/src/net/http/h2_bundle.go:1517 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4200120e0, 0xc4203e3c50, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1775 +0xa4
net/http.(*http2clientConnReadLoop).run(0xc429345fb8, 0xdb67d0, 0xc429184fb8)
        /usr/local/go/src/net/http/h2_bundle.go:8028 +0x90
net/http.(*http2ClientConn).readLoop(0xc420272e00)
        /usr/local/go/src/net/http/h2_bundle.go:7956 +0x68
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:7143 +0x65c
```

**Comment by gilbertchen** [comment]
Since the segmentation fault didn't happen in Duplicacy's code, it looks to me more like a random memory problem.  If you consistently encounter the same issue I'll look into it more deeply.
