### ISSUE TITLE
duplicacy cat bigfile runtime out of memory

### ISSUE THREAD

**Issue by Mehuge** [gilbertchen/duplicacy#560]
I am testing `duplicacy` with backing up large files, for my test I am using a 16gb /dev/urandom generated file, so probably little deduplication. One of the reasons we are looking for an alternative to `rdiff-backup` is because `rdiff-backup` has problems dealing with large files.

`duplicacy backup` 
works fine. Took 16 minutes (local backup target)

`duplicacy restore` 
`duplicacy restore bigfile` 
works both for whole repository and for just the bigfile file, and takes about the same time as it took to backup.

`duplicacy cat bigfile`
crashes with out of memory after running for 33 minutes.

```
adf (linuxlap) > time duplicacy cat bigfile >bigfile2
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xd8dda3, 0x16)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc729ac0000, 0x1df660000, 0x7ab500, 0x12fc918)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x12e33e0, 0x1df660000, 0x7f0862784010)
        /usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x12e33e0, 0xefb2d, 0x0)
        /usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x12e33e0, 0xefb2d, 0x12fc928, 0xc400000001)
        /usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x12e33e0, 0xefb2d, 0x101, 0xc41ff45aff)
        /usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x12e33e0, 0xefb2d, 0xc420000101, 0x43b755)
        /usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x1df65a000, 0x100, 0x1)
        /usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1175

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc42136b130 sp=0xc42136b128 pc=0x4572a0
runtime.mallocgc(0x1df65a000, 0x0, 0xc58200, 0xc42017e480)
        /usr/local/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc42136b1d0 sp=0xc42136b130 pc=0x4105f2
runtime.growslice(0xbfc7a0, 0xc575976000, 0x17f0acb9d, 0x17f848000, 0x1800755c5, 0xc420183e00, 0x4f0, 0xc4200c20f0)
        /usr/local/go/src/runtime/slice.go:172 +0x21d fp=0xc42136b238 sp=0xc42136b1d0 pc=0x4417dd
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).PrintFile.func1(0xc425154000, 0xfc8a28, 0x214f3ba)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:1273 +0xdf fp=0xc42136b2a8 sp=0xc42136b238 pc=0xb4f12f
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).RetrieveFile(0xc420080080, 0xc420246000, 0xc420250c00, 0xc42136b4e0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:1200 +0x389 fp=0xc42136b450 sp=0xc42136b2a8 pc=0xb2dbf9
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).PrintFile(0xc420080080, 0xc4200be2c0, 0x11, 0x0, 0x7fff50a540c4, 0x7, 0xc4200be2e0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:1273 +0x306 fp=0xc42136b5b8 sp=0xc42136b450 pc=0xb2e7f6
main.printFile(0xc4200d2fc0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:961 +0x386 fp=0xc42136b6c8 sp=0xc42136b5b8 pc=0xb5c576
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.Command.Run(0xd7c1ef, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdb030b, 0x53, 0x0, ...)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/command.go:160 +0x7ea fp=0xc42136b920 sp=0xc42136b6c8 pc=0x72ca8a
github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli.(*App).Run(0xc4201b1b00, 0xc4200a6150, 0x3, 0x3, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/vendor/github.com/gilbertchen/cli/app.go:179 +0x864 fp=0xc42136be30 sp=0xc42136b920 pc=0x72a484
main.main()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2008 +0x584c fp=0xc42136df88 sp=0xc42136be30 pc=0xb6510c
runtime.main()
        /usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc42136dfe0 sp=0xc42136df88 pc=0x42c4b2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42136dfe8 sp=0xc42136dfe0 pc=0x459cb1

goroutine 18 [syscall, 33 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 33 [select, 33 minutes, locked to thread]:
runtime.gopark(0xdb9400, 0x0, 0xd7eaeb, 0x6, 0x18, 0x1)
        /usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc4202ca750, 0xc4201902a0)
        /usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 20 [chan receive, 33 minutes]:
main.main.func1(0xc42017da40)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2002 +0x60
created by main.main
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:2001 +0x581a

goroutine 5 [select]:
github.com/gilbertchen/duplicacy/src.CreateChunkDownloader.func1(0xc4201b4000, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:80 +0x190
created by github.com/gilbertchen/duplicacy/src.CreateChunkDownloader
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkdownloader.go:77 +0x223
```

**Comment by Mehuge** [comment]
In case it is helpful, this is the output from -d -v

```
Chunk read levels: [1], write level: 1
Compression level: 100
Average chunk size: 4194304
Maximum chunk size: 16777216
Minimum chunk size: 1048576
Chunk seed: 6475706c6963616379
id: linuxlap_adf_proj, revision: 0, path: bigfile
Downloading latest revision for snapshot linuxlap_adf_proj
Listing revisions for snapshot linuxlap_adf_proj
Downloaded file snapshots/linuxlap_adf_proj/1
Chunk 7518035149b0a8972f6d039e8265567e14256feea033901f032e4bcb194b905a has been downloaded
Fetching chunk e3f99cb6e6524e7a23e04c657a9abf7a5e71885ab92414a6464825eab13c129d
Chunk e3f99cb6e6524e7a23e04c657a9abf7a5e71885ab92414a6464825eab13c129d has been downloaded
... ( 1262 other fetches/downloads )...
Fetching chunk 089a3c181c69c82f21d1168b5a3a812634eee1e952e0c59fee38e821fc799ff5
Chunk 089a3c181c69c82f21d1168b5a3a812634eee1e952e0c59fee38e821fc799ff5 has been downloaded
```

Also, I used lsof to monitor what it was doing and for a long time, after accessing

```
duplicacy 12839  adf    3r      REG  253,2  3092978 806649488 /home/adf/backups/chunks/f5/e90da585a40e3de026ce84967d7ae3a5c36f3bccf95559232ed736dff932b
```

it didn't access any other files before crashing.

**Comment by gilbertchen** [comment]
Fixed by https://github.com/gilbertchen/duplicacy/commit/458687d543a03b6e6a74d2a6a20b5b8bc81062d8.
