### ISSUE TITLE
runtime error: integer divide by zero when removing a snapshot

### ISSUE THREAD

**Issue by vrusinov** [gilbertchen/duplicacy#65]
```
# duplicacy -v prune -id $id -r 1
Storage set to gcd://backups/duplicacy
Listing all snapshot ids
Listing revisions for snapshot <...>
Listing revisions for snapshot <...>
Listing revisions for snapshot $id
<...>
Listing revisions for snapshot <...>
Fossil collection 4 found
New snapshot $id revision 8 doesn't meet the fossil deletion criteria
New snapshot <...> revision 31 doesn't meet the fossil deletion criteria
No new snapshot from <...> since the fossil collection step
New snapshot <...> revision 13 doesn't meet the fossil deletion criteria
<....>
No new snapshot from <...> since the fossil collection step
Fossils from collection 4 can't be deleted because deletion criteria aren't met
Fossil collection 5 found
<...>
No new snapshot from $id since the fossil collection step
Fossils from collection 5 can't be deleted because deletion criteria aren't met
runtime error: integer divide by zero
goroutine 461 [running]:
runtime/debug.Stack(0x26, 0x0, 0x0)
	/home/gchen/go1.8.1/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/home/gchen/go1.8.1/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy.CatchLogException()
	/home/gchen/go/src/github.com/gilbertchen/duplicacy/duplicacy_log.go:173 +0x1a1
panic(0xa92980, 0xe964e0)
	/home/gchen/go1.8.1/go/src/runtime/panic.go:489 +0x2cf
github.com/gilbertchen/duplicacy.(*ChunkDownloader).Download(0xc424dd0780, 0x0, 0x0, 0x39, 0xc42032c180, 0x20, 0x0, 0x1, 0xc420014200)
	/home/gchen/go/src/github.com/gilbertchen/duplicacy/duplicacy_chunkdownloader.go:370 +0xc61
github.com/gilbertchen/duplicacy.CreateChunkDownloader.func1(0xc424dd0780, 0x0)
	/home/gchen/go/src/github.com/gilbertchen/duplicacy/duplicacy_chunkdownloader.go:81 +0x161
created by github.com/gilbertchen/duplicacy.CreateChunkDownloader
	/home/gchen/go/src/github.com/gilbertchen/duplicacy/duplicacy_chunkdownloader.go:86 +0x23f
```

I have an issue with some other snapshot (it complains about missing chunks), but still, it should not fail with ugly trace and division by zero.

**Comment by vrusinov** [comment]
Forgot to add: I'm using 2.0.0 downloaded from here.
