### ISSUE TITLE
Win32 Build 

### ISSUE THREAD

**Issue by naeloob** [gilbertchen/duplicacy#74]
Hey, that seems to be a great soft, congrats for that.
I will make some test to see if it fits with my requeriments.

I wonder if it's possible to get Win32 builds.

Thanks in Advance.

Best Regards

**Comment by gilbertchen** [comment]
I just uploaded the Win32 build to the release page.

**Comment by naeloob** [comment]
Thank you!!!
Testing.

Any problem mixing distinct Arquitecture/SO duplicacy backups on the same snapshot/storage?
I mean, one Linux64, win32 and win64 backup on the same snapshot/storage in order to share chunks.

**Comment by naeloob** [comment]
Well, i'm sorry to bring bad news...

Storage : GoogleDrive encrypted
Backup : -vss -t Init -threads 4 -stats


I have this error (sorry i  didnt save on file just console and it's not full log) : 

```
google.golang.org/api/drive/v3.(*FilesCreateCall).Do(0x15085b40, 0x0, 0x0, 0x0,0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/google.golang.org/api/drive/v3/drive-gen.go:4176 +0x76
github.com/gilbertchen/duplicacy/src.(*GCDStorage).UploadFile(0x1276b5a0, 0x0, 0x17673b30, 0x47, 0x21d1a000, 0x3b2382, 0x3008935, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_gcdstorage.go:592 +0x316
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Upload(0x14bfe420, 0x0, 0x149a0000, 0x561, 0x16b54001)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:132 +0x34d
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start.func1(0x14bfe420, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:60 +0xd1
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:65 +0x44

goroutine 70 [IO wait]:
net.runtime_pollWait(0x339b0f78, 0x72, 0xc4c1e4)
        /usr/local/go/src/runtime/netpoll.go:164 +0x4b
net.(*pollDesc).wait(0x16854c28, 0x72, 0xc4c1e4, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x2b
net.(*ioSrv).ExecIO(0x12782020, 0x16854b78, 0x9cef2c, 0x7, 0x9fa730, 0x0, 0x0, 0xd)
        /usr/local/go/src/net/fd_windows.go:196 +0xb9
net.(*netFD).Read(0x16854b40, 0x13967000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:452 +0xec
net.(*conn).Read(0x1763aa40, 0x13967000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x56
crypto/tls.(*block).readFromUntil(0x16843140, 0x339b0ff0, 0x1763aa40, 0x5, 0x1763aa40, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:488 +0x79
crypto/tls.(*Conn).readRecord(0x16f2ca00, 0x9fab17, 0x16f2caa0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:590 +0xa4
crypto/tls.(*Conn).Read(0x16f2ca00, 0x16b53000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1134 +0xed
bufio.(*Reader).Read(0x146018c0, 0x1757d5a0, 0x9, 0x9, 0x10, 0x127c1740, 0x1e765bc)
        /usr/local/go/src/bufio/bufio.go:213 +0x232
io.ReadAtLeast(0xc4cf90, 0x146018c0, 0x1757d5a0, 0x9, 0x9, 0x9, 0x127c1730, 0x98bfc0, 0x16005de0)
        /usr/local/go/src/io/io.go:307 +0x7c
io.ReadFull(0xc4cf90, 0x146018c0, 0x1757d5a0, 0x9, 0x9, 0x126a4024, 0x126a4000,0x16854c30)
        /usr/local/go/src/io/io.go:325 +0x45
net/http.http2readFrameHeader(0x1757d5a0, 0x9, 0x9, 0xc4cf90, 0x146018c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:781 +0x66
net/http.(*http2Framer).ReadFrame(0x1757d580, 0x127c1740, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1008 +0x78
net/http.(*http2clientConnReadLoop).run(0x16005fd8, 0x9fa80c, 0x12799fd8)
        /usr/local/go/src/net/http/h2_bundle.go:6626 +0x65
net/http.(*http2ClientConn).readLoop(0x13c95000)
        /usr/local/go/src/net/http/h2_bundle.go:6555 +0x96
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:5880 +0x626

goroutine 39 [select]:
net/http.(*http2ClientConn).RoundTrip(0x13c95000, 0x16a87800, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:6155 +0x952
net/http.(*http2Transport).RoundTripOpt(0x1269dd70, 0x16a87800, 0x0, 0x4096ca, 0x9cd2ab, 0x16788e40)
        /usr/local/go/src/net/http/h2_bundle.go:5691 +0x122
net/http.(*http2Transport).RoundTrip(0x1269dd70, 0x16a87800, 0x1660a020, 0x0, 0x4010b1)
        /usr/local/go/src/net/http/h2_bundle.go:5653 +0x34
net/http.http2noDialH2RoundTripper.RoundTrip(0x1269dd70, 0x16a87800, 0x16788e40, 0x5, 0x126ffcf8)
        /usr/local/go/src/net/http/h2_bundle.go:345 +0x2d
net/http.(*Transport).RoundTrip(0xc8c860, 0x16a87800, 0x16a87800, 0x0, 0x4)
        /usr/local/go/src/net/http/transport.go:349 +0x88d
golang.org/x/oauth2.(*Transport).RoundTrip(0x1276b540, 0x16a87780, 0x1276b540, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/golang.org/x/oauth2/transport.go:48 +0xac
net/http.send(0x16a87780, 0xc4d5d0, 0x1276b540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12801600, 0x160c8dd0, ...)
        /usr/local/go/src/net/http/client.go:249 +0x137
net/http.(*Client).send(0x1276b560, 0x16a87780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x40ceac, 0x80)
        /usr/local/go/src/net/http/client.go:173 +0xc9
net/http.(*Client).Do(0x1276b560, 0x16a87780, 0x0, 0x3, 0x16788e40)
        /usr/local/go/src/net/http/client.go:595 +0x1fa
google.golang.org/api/gensupport.SendRequest(0x0, 0x0, 0x1276b560, 0x16a87780, 0x3411cea0, 0x127c11a0, 0x16a87780)
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/send.go:36 +0x1b3
google.golang.org/api/drive/v3.(*FilesCreateCall).doRequest(0x15085180, 0x9cc7e5, 0x4, 0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/google.golang.org/api/drive/v3/drive-gen.go:4164 +0x4fa
google.golang.org/api/drive/v3.(*FilesCreateCall).Do(0x15085180, 0x0, 0x0, 0x0,0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/google.golang.org/api/drive/v3/drive-gen.go:4176 +0x76
github.com/gilbertchen/duplicacy/src.(*GCDStorage).UploadFile(0x1276b5a0, 0x2, 0x175a23c0, 0x47, 0x26736000, 0x56c402, 0x120247a, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_gcdstorage.go:592 +0x316
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Upload(0x14bfe420, 0x2, 0x149a0180, 0x55f, 0x1)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:132 +0x34d
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start.func1(0x14bfe420, 0x2)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:60 +0xd1
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:65 +0x44

goroutine 40 [select]:
net/http.(*http2ClientConn).RoundTrip(0x13c95000, 0x16a87f80, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:6155 +0x952
net/http.(*http2Transport).RoundTripOpt(0x1269dd70, 0x16a87f80, 0x0, 0x4096ca, 0x9cd2ab, 0x140f6480)
        /usr/local/go/src/net/http/h2_bundle.go:5691 +0x122
net/http.(*http2Transport).RoundTrip(0x1269dd70, 0x16a87f80, 0x1660a9e0, 0x0, 0x4010b1)
        /usr/local/go/src/net/http/h2_bundle.go:5653 +0x34
net/http.http2noDialH2RoundTripper.RoundTrip(0x1269dd70, 0x16a87f80, 0x140f6480, 0x5, 0x126ffcf8)
        /usr/local/go/src/net/http/h2_bundle.go:345 +0x2d
net/http.(*Transport).RoundTrip(0xc8c860, 0x16a87f80, 0x16a87f80, 0x0, 0x4)
        /usr/local/go/src/net/http/transport.go:349 +0x88d
golang.org/x/oauth2.(*Transport).RoundTrip(0x1276b540, 0x16a87f00, 0x1276b540, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/golang.org/x/oauth2/transport.go:48 +0xac
net/http.send(0x16a87f00, 0xc4d5d0, 0x1276b540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x128018e0, 0x160c8eb8, ...)
        /usr/local/go/src/net/http/client.go:249 +0x137
net/http.(*Client).send(0x1276b560, 0x16a87f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x40ceac, 0x80)
        /usr/local/go/src/net/http/client.go:173 +0xc9
net/http.(*Client).Do(0x1276b560, 0x16a87f00, 0x0, 0x3, 0x140f6480)
        /usr/local/go/src/net/http/client.go:595 +0x1fa
google.golang.org/api/gensupport.SendRequest(0x0, 0x0, 0x1276b560, 0x16a87f00, 0x3411cea0, 0x127c13c0, 0x16a87f00)
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/send.go:36 +0x1b3
google.golang.org/api/drive/v3.(*FilesCreateCall).doRequest(0x15085700, 0x9cc7e5, 0x4, 0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/google.golang.org/api/drive/v3/drive-gen.go:4164 +0x4fa
google.golang.org/api/drive/v3.(*FilesCreateCall).Do(0x15085700, 0x0, 0x0, 0x0,0x0, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/google.golang.org/api/drive/v3/drive-gen.go:4176 +0x76
github.com/gilbertchen/duplicacy/src.(*GCDStorage).UploadFile(0x1276b5a0, 0x3, 0x175a2870, 0x47, 0x187a0000, 0x304cbc, 0x1000000, 0x0, 0x0)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_gcdstorage.go:592 +0x316
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Upload(0x14bfe420, 0x3, 0x149a0360, 0x560, 0x1)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:132 +0x34d
github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start.func1(0x14bfe420, 0x3)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:60 +0xd1
created by github.com/gilbertchen/duplicacy/src.(*ChunkUploader).Start
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_chunkuploader.go:65 +0x44

goroutine 3963 [runnable]:
sync.runtime_notifyListWait(0x16b4ec68, 0x6c39)
        /usr/local/go/src/runtime/sema.go:298 +0x114
sync.(*Cond).Wait(0x16b4ec60)
        /usr/local/go/src/sync/cond.go:57 +0x6e
net/http.(*http2clientStream).awaitFlowControl(0x1660aa50, 0x4000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:6358 +0xf0
net/http.(*http2clientStream).writeRequestBody(0x1660aa50, 0x3411cea0, 0x127c13c0, 0x3411ceb8, 0x127c13c0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:6276 +0x1ac
net/http.(*http2Transport).getBodyWriterState.func1()
        /usr/local/go/src/net/http/h2_bundle.go:7315 +0xaa
created by net/http.http2bodyWriterState.scheduleBodyWrite
        /usr/local/go/src/net/http/h2_bundle.go:7359 +0x77

goroutine 3965 [runnable]:
sync.runtime_notifyListWait(0x16b4ec68, 0x6c3b)
        /usr/local/go/src/runtime/sema.go:298 +0x114
sync.(*Cond).Wait(0x16b4ec60)
        /usr/local/go/src/sync/cond.go:57 +0x6e
net/http.(*http2clientStream).awaitFlowControl(0x1660b290, 0x9d, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:6358 +0xf0
net/http.(*http2clientStream).writeRequestBody(0x1660b290, 0x3411cea0, 0x127c15e0, 0x3411ceb8, 0x127c15e0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:6276 +0x1ac
net/http.(*http2Transport).getBodyWriterState.func1()
        /usr/local/go/src/net/http/h2_bundle.go:7315 +0xaa
created by net/http.http2bodyWriterState.scheduleBodyWrite
        /usr/local/go/src/net/http/h2_bundle.go:7359 +0x77

goroutine 3962 [semacquire]:
sync.runtime_notifyListWait(0x16a87dcc, 0x3)
        /usr/local/go/src/runtime/sema.go:298 +0x114
sync.(*Cond).Wait(0x16a87dc4)
        /usr/local/go/src/sync/cond.go:57 +0x6e
io.(*pipe).write(0x16a87d80, 0x301b2000, 0x304cbc, 0x800000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:90 +0x13e
io.(*PipeWriter).Write(0x160c8e80, 0x301b2000, 0x304cbc, 0x800000, 0x0, 0x0, 0xe205ef63)
        /usr/local/go/src/io/pipe.go:157 +0x3b
mime/multipart.(*part).Write(0x127b7e30, 0x301b2000, 0x304cbc, 0x800000, 0x127b7e30, 0x126955e0, 0x40acf0)
        /usr/local/go/src/mime/multipart/writer.go:185 +0xad
bytes.(*Reader).WriteTo(0x128017c0, 0xc4da90, 0x127b7e30, 0x3411ced0, 0x128017c0, 0x5f151901, 0x924860)
        /usr/local/go/src/bytes/reader.go:134 +0xbd
io.copyBuffer(0xc4da90, 0x127b7e30, 0xc4d010, 0x128017c0, 0x0, 0x0, 0x0, 0x0, 0x4000105, 0x0, ...)
        /usr/local/go/src/io/io.go:380 +0x29c
io.Copy(0xc4da90, 0x127b7e30, 0xc4d010, 0x128017c0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:360 +0x51
google.golang.org/api/gensupport.newMultipartReader.func1(0x12801840, 0x2, 0x2,0x12801880, 0x160c8e80)
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/media.go:128 +0xa2
created by google.golang.org/api/gensupport.newMultipartReader
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/media.go:138 +0x1b3

goroutine 3964 [semacquire]:
sync.runtime_notifyListWait(0x16aca0cc, 0x2)
        /usr/local/go/src/runtime/sema.go:298 +0x114
sync.(*Cond).Wait(0x16aca0c4)
        /usr/local/go/src/sync/cond.go:57 +0x6e
io.(*pipe).write(0x16aca080, 0x16d45970, 0x6c, 0xac, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:90 +0x13e
io.(*PipeWriter).Write(0x160c8f40, 0x16d45970, 0x6c, 0xac, 0x4, 0x1, 0x44da68)
        /usr/local/go/src/io/pipe.go:157 +0x3b
bytes.(*Buffer).WriteTo(0x13b72ea0, 0xc4da10, 0x160c8f40, 0x34934900, 0x13b72ea0, 0x1, 0x4abfb2)
        /usr/local/go/src/bytes/buffer.go:212 +0xae
io.copyBuffer(0xc4da10, 0x160c8f40, 0xc4cfd0, 0x13b72ea0, 0x0, 0x0, 0x0, 0x2, 0x174f4000, 0x0, ...)
        /usr/local/go/src/io/io.go:380 +0x29c
io.Copy(0xc4da10, 0x160c8f40, 0xc4cfd0, 0x13b72ea0, 0x0, 0x0, 0x0, 0x2)
        /usr/local/go/src/io/io.go:360 +0x51
mime/multipart.(*Writer).CreatePart(0x12801b40, 0x144dbde0, 0x144dbde0, 0x140f65a0, 0x9d, 0x0)
        /usr/local/go/src/mime/multipart/writer.go:110 +0x423
google.golang.org/api/gensupport.newMultipartReader.func1(0x12801b00, 0x2, 0x2,0x12801b40, 0x160c8f40)
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/media.go:122 +0x66
created by google.golang.org/api/gensupport.newMultipartReader
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/media.go:138 +0x1b3

goroutine 3960 [semacquire]:
sync.runtime_notifyListWait(0x16a8774c, 0x3)
        /usr/local/go/src/runtime/sema.go:298 +0x114
sync.(*Cond).Wait(0x16a87744)
        /usr/local/go/src/sync/cond.go:57 +0x6e
io.(*pipe).write(0x16a87700, 0x2f1e4000, 0x56c402, 0x800000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:90 +0x13e
io.(*PipeWriter).Write(0x160c8d98, 0x2f1e4000, 0x56c402, 0x800000, 0x0, 0x0, 0xe205ef63)
        /usr/local/go/src/io/pipe.go:157 +0x3b
mime/multipart.(*part).Write(0x127c1280, 0x2f1e4000, 0x56c402, 0x800000, 0x127c1280, 0x160c8e08, 0x40acf0)
        /usr/local/go/src/mime/multipart/writer.go:185 +0xad
bytes.(*Reader).WriteTo(0x128014a0, 0xc4da90, 0x127c1280, 0x3411ced0, 0x128014a0, 0x7581d701, 0x924860)
        /usr/local/go/src/bytes/reader.go:134 +0xbd
io.copyBuffer(0xc4da90, 0x127c1280, 0xc4d010, 0x128014a0, 0x0, 0x0, 0x0, 0x0, 0x2000107, 0x0, ...)
        /usr/local/go/src/io/io.go:380 +0x29c
io.Copy(0xc4da90, 0x127c1280, 0xc4d010, 0x128014a0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:360 +0x51
google.golang.org/api/gensupport.newMultipartReader.func1(0x12801560, 0x2, 0x2,0x128015a0, 0x160c8d98)
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/media.go:128 +0xa2
created by google.golang.org/api/gensupport.newMultipartReader
        /Users/chgang/zincbox/go/src/google.golang.org/api/gensupport/media.go:138 +0x1b3

goroutine 3961 [runnable]:
sync.runtime_notifyListWait(0x16b4ec68, 0x6c3a)
        /usr/local/go/src/runtime/sema.go:298 +0x114
sync.(*Cond).Wait(0x16b4ec60)
        /usr/local/go/src/sync/cond.go:57 +0x6e
net/http.(*http2clientStream).awaitFlowControl(0x1660a0b0, 0x1cd, 0x0, 0x0, 0x0)

        /usr/local/go/src/net/http/h2_bundle.go:6358 +0xf0
net/http.(*http2clientStream).writeRequestBody(0x1660a0b0, 0x3411cea0, 0x127c11a0, 0x3411ceb8, 0x127c11a0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:6276 +0x1ac
net/http.(*http2Transport).getBodyWriterState.func1()
        /usr/local/go/src/net/http/h2_bundle.go:7315 +0xaa
created by net/http.http2bodyWriterState.scheduleBodyWrite
        /usr/local/go/src/net/http/h2_bundle.go:7359 +0x77


```

retry? or make it on another storage path?

**Comment by gilbertchen** [comment]
It ran out of memory.  How many files do you have under the directory to be backed up?  You can try to exclude some subdirectories and try again.

**Comment by naeloob** [comment]
Full Hard Drive, at this moment i don't know how many files, but a lot for sure.

I thought that, but total memory don't go up more than 20% used.

**Comment by naeloob** [comment]
Well, no so much files as i thought...
Just 141K.

It index all files whitout problem, but fails uploading chunks, at 6.5% aprox.
It uploads about 1100 chunks before fail.

Duplicacy process uses 120-140 Kb of ram until starts to grow to 600-700 Kb and then broke and fail.

Hope this helps.

Regards.

**Comment by gilbertchen** [comment]
Did you mean 600-700MB?

Go on 32 bit Windows used to have a limit of 512MB on the heap size; not sure if it is still the case in Go 1.8.  The stack trace clearly showed that the error occurred when it was trying to allocate a buffer about 16MB, so it could be that it simply ran out of heap size.

**Comment by naeloob** [comment]
Yes, sorry, i mean 600-700 MB.
But the problem arises uploading chunks, after completed the index.

Now test reducing -threads 4 to -threads 2, it seems to work... 2K chunks uploaded, about 12,3%.
Memory used by duplicacy is about 400MB.
Is there info about how much memory gets every upload thread?
Any way to change the heap size?

I will update the post with new info.

**Comment by gilbertchen** [comment]
Every upload thread needs its own chunk buffer, which is about 16MB.

**Comment by naeloob** [comment]
Thanks for the info.

Now i'm testing another hdd and the log file says "Discarding file attributes", i have set the enviroment variable DUPLICACY_ATTRIBUTE_THRESHOLD to 100.000.000 but it stills appear the message. I have no 100.000.000 files. In fact the same message appear setting the variable to the int32 size.

Any clue what happens?
Why make discard the file attributes if there's a high number of files? to save memory?

**Comment by gilbertchen** [comment]
That message is somewhat misleading -- it doesn't mean that Duplicacy isn't saving the file attributes; instead it just discards file attributes that have been loaded in order to save memory.  Later when it is uploading the snapshot it will read in file attributes again and save them.

The default value for DUPLICACY_ATTRIBUTE_THRESHOLD is 1000000.  You should set it to a smaller value only if you run out of memory.

**Comment by naeloob** [comment]
Thank you for the information.

But it seems not to apply the enviroment variable.
I've executed : 

set DUPLICACY_ATTRIBUTE_THRESHOLD = 1
duplicacy backup ....

And after 10 minutes of indexing still does not appear "Discarding file attributes" on the log file, and for sure it has indexed more than 1 file.

**Comment by gilbertchen** [comment]
Here is the output from my test:

```
C:\Temp\repository>set DUPLICACY_ATTRIBUTE_THRESHOLD=1

C:\Temp\repository>duplicacy_win_x64_2.0.3.exe backup -stats
Storage set to c:\Temp\storage
No previous backup found
Indexing C:\Temp\repository
Discarding file attributes
```

I suspect it is the spaces in `set DUPLICACY_ATTRIBUTE_THRESHOLD = 1` that gave you the trouble.

**Comment by naeloob** [comment]
Yeah!! 
You're Right. without spaces works.

Thank you.
