### ISSUE TITLE
HubiC TLS timeout: Failed to list the revisions of the snapshot

### ISSUE THREAD

**Issue by phretor** [gilbertchen/duplicacy#86]
Hello!

I've stumbled upon this error with the HubiC backend (I'm blaming the backend, which is not responding quickly enough, apparently; maybe a timeout option would be helpful). HubiC recently capped their bandwidth to 10Mbps, I guess to avoid unfair use (I can tell, after giving out 10TB for $50/mo, people are going crazy).

After a 4–5 hours of non-interrupted upload to the HubiC backend, I get this error, and I keep getting it whenever I try to restart the incomplete backup.

Here's some context:

```
# cd /data/media

# cat .duplicacy/preferences
[
    {
        "name": "default",
        "id": "hubic_tank_media",
        "storage": "hubic://tank/media",
        "encrypted": true,
        "no_backup": false,
        "no_restore": false,
        "no_save_password": false,
        "keys": null
    }

# cat ~/bin/dup.sh
#! /bin/bash

DUP=$HOME/go/bin/duplicacy

source $HOME/bin/dup_pre.sh

$DUP $@

source $HOME/bin/dup_post.sh

# cat ~/bin/dup_pre.sh
export DUPLICACY_PASSWORD="************************"
export DUPLICACY_HUBIC_TOKEN=$HOME/hubic-token.json

# cat $HOME/hubic-token.json
{"access_token":"*****","token_type":"Bearer","refresh_token":"*****","expiry":"2017-07-04T12:03:41.997933356Z"}

# cat ~/bin/dup_post.sh
unset DUPLICACY_PASSWORD
unset DUPLICACY_HUBIC_TOKEN

# ~/bin/dup.sh -v -d -stack backup
```

And here is the (shortened) log, from which I've removed only my (private) path names (substitute with `Listing [...]` and so on) and redacted the `AUTH_***` part of the HubiC API endpoint.

```
Storage set to hubic://tank/media
Reading the environment variable DUPLICACY_HUBIC_TOKEN
GET https://api.hubic.com/1.0/account/credentials
HEAD https://lb1.hubic.ovh.net/v1/AUTH_***/default/tank/media
HEAD https://lb1.hubic.ovh.net/v1/AUTH_***/default/tank/media/chunks
HEAD https://lb1.hubic.ovh.net/v1/AUTH_***/default/tank/media/snapshots
Failed to store the value to the keyring: keyring: No suitable keyring provider found (check your build flags)
Reading the environment variable DUPLICACY_PASSWORD
HEAD https://lb1.hubic.ovh.net/v1/AUTH_***/default/tank/media/config
GET https://lb1.hubic.ovh.net/v1/AUTH_***/default/tank/media/config
Compression level: 100
Average chunk size: 4194304
Maximum chunk size: 16777216
Minimum chunk size: 1048576
Chunk seed: ec0b9e3677594d0bdcdd66a3dbc775917c09c4e6bf3591e02120fbfda6c2506e
Failed to store the value to the keyring: keyring: No suitable keyring provider found (check your build flags)
top: /data/media, quick: true, tag:
Downloading latest revision for snapshot hubic_tank_media
Listing revisions for snapshot hubic_tank_media
PUT https://lb1.hubic.ovh.net/v1/AUTH_***/default/tank/media/snapshots/hubic_tank_media
GET https://lb1.hubic.ovh.net/v1/AUTH_***/default?format=json&limit=1000&delimiter=%2f&prefix=tank%2Fmedia%2Fsnapshots%2Fhubic_tank_media%2F
No previous backup found
Indexing /data/media
Listing [...]
Packing [...]
Packed [...]
Failed to find the path for the chunk d63b58ae841f5764ba920e701af6bb8a9ba19178f11f13fd032d706662ccd126: Head https://lb1.hubic.ovh.net/v1/AUTH_***/default/tank/media/chunks/d63b58ae841f5764ba920e701af6bb8a9ba19178f11f13fd032d706662ccd126: net/http: TLS handshake timeout
Incomplete snapshot saved to /data/media/.duplicacy/incomplete
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0xc420568f08)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy/src.CatchLogException()
        /root/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:171 +0x13d
panic(0xc1c1c0, 0xc420375b60)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/gilbertchen/duplicacy/src.logf(0x2, 0xcc206d, 0xd, 0xcdefae, 0x33, 0xc420569370, 0x2, 0x2)
        /root/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:154 +0x1ac
github.com/gilbertchen/duplicacy/src.LOG_ERROR(0xcc206d, 0xd, 0xcdefae, 0x33, 0xc420569370, 0x2, 0x2)
        /root/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_log.go:97 +0x73
github.com/gilbertchen/duplicacy/src.(*SnapshotManager).downloadLatestSnapshot(0xc4203cb740, 0xc420014620, 0x10, 0x1b)
        /root/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_snapshotmanager.go:545 +0x2e2
github.com/gilbertchen/duplicacy/src.(*BackupManager).Backup(0xc420052980, 0xc420014034, 0xb, 0x1, 0x1, 0x0, 0x0, 0x0, 0xcbde00)
        /root/go/src/github.com/gilbertchen/duplicacy/src/duplicacy_backupmanager.go:165 +0x2be
main.backupRepository(0xc420012240)
        /root/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:620 +0x4c9
github.com/gilbertchen/cli.Command.Run(0xcbb38a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcdd9a3, 0x30, 0x0, ...)
        /root/go/src/github.com/gilbertchen/cli/command.go:160 +0x8bc
github.com/gilbertchen/cli.(*App).Run(0xc420152c60, 0xc420060050, 0x5, 0x5, 0x0, 0x0)
        /root/go/src/github.com/gilbertchen/cli/app.go:179 +0x8e3
main.main()
        /root/go/src/github.com/gilbertchen/duplicacy/duplicacy/duplicacy_main.go:1698 +0x49ff
```

I'm on 2.0.4 running on FreeBSD 11.0-RELEASE-p1 with go1.8 freebsd/amd64.

**Comment by gilbertchen** [comment]
I wonder if this is how they do the rate limiting.  Did they allow to connect after, say, an hour?

The fix would to be to retry on the TLS timeout error.

**Comment by phretor** [comment]
@gilbertchen I retried after a while, not sure how long. I've retried when I realized that the backup had failed.

Honestly, I'm not really into trusting a service that uses non-standard ways of throttling the bandwidth.

Are you aware of other duplicacy users having experienced this type of timeout errors?

**Comment by gilbertchen** [comment]
I guess there aren't many duplicacy users who use HubiC.  The Duplicacy/HubiC backend is very slow, only because they don't allow https connections to be reused, so for every request Duplicacy has to spend at least one second to establish a new https connection.

**Comment by gilbertchen** [comment]
My nightly test script started to get the same TLS timeout errors earliest today.  So I increased the TLS timeout from the default 10 seconds to 60 seconds.  That seemed to work for the TLS handshake part, but then a different error followed:

```
duplicacy_storage_test.go:252: Failed to create directory snapshots: Put https://lb9911.hubic.ovh.net/v1/AUTH_*/default/test/storage/snapshots: net/http: timeout awaiting response headers
```

So it looks like they are not using the TLS handshake timeout for rate-limiting -- it is just that their servers are overloaded.
